/**
 * MoveNet Pose landmark indices and connections
 * Based on MoveNet model with 17 keypoints
 * Compatible with both MediaPipe (33 landmarks) and MoveNet (17 keypoints)
 */

// MoveNet pose keypoint indices (17 keypoints)
export const MOVENET_LANDMARKS = {
  NOSE: 0,
  LEFT_EYE: 1,
  RIGHT_EYE: 2,
  LEFT_EAR: 3,
  RIGHT_EAR: 4,
  LEFT_SHOULDER: 5,
  RIGHT_SHOULDER: 6,
  LEFT_ELBOW: 7,
  RIGHT_ELBOW: 8,
  LEFT_WRIST: 9,
  RIGHT_WRIST: 10,
  LEFT_HIP: 11,
  RIGHT_HIP: 12,
  LEFT_KNEE: 13,
  RIGHT_KNEE: 14,
  LEFT_ANKLE: 15,
  RIGHT_ANKLE: 16,
};

// MediaPipe pose landmark indices (33 landmarks) - for future use
export const POSE_LANDMARKS = {
  NOSE: 0,
  LEFT_EYE_INNER: 1,
  LEFT_EYE: 2,
  LEFT_EYE_OUTER: 3,
  RIGHT_EYE_INNER: 4,
  RIGHT_EYE: 5,
  RIGHT_EYE_OUTER: 6,
  LEFT_EAR: 7,
  RIGHT_EAR: 8,
  MOUTH_LEFT: 9,
  MOUTH_RIGHT: 10,
  LEFT_SHOULDER: 11,
  RIGHT_SHOULDER: 12,
  LEFT_ELBOW: 13,
  RIGHT_ELBOW: 14,
  LEFT_WRIST: 15,
  RIGHT_WRIST: 16,
  LEFT_PINKY: 17,
  RIGHT_PINKY: 18,
  LEFT_INDEX: 19,
  RIGHT_INDEX: 20,
  LEFT_THUMB: 21,
  RIGHT_THUMB: 22,
  LEFT_HIP: 23,
  RIGHT_HIP: 24,
  LEFT_KNEE: 25,
  RIGHT_KNEE: 26,
  LEFT_ANKLE: 27,
  RIGHT_ANKLE: 28,
  LEFT_HEEL: 29,
  RIGHT_HEEL: 30,
  LEFT_FOOT_INDEX: 31,
  RIGHT_FOOT_INDEX: 32,
};

// MoveNet pose connections for drawing skeleton (17 keypoints)
export const MOVENET_CONNECTIONS = [
  // Face
  [MOVENET_LANDMARKS.LEFT_EYE, MOVENET_LANDMARKS.RIGHT_EYE],
  [MOVENET_LANDMARKS.NOSE, MOVENET_LANDMARKS.LEFT_EYE],
  [MOVENET_LANDMARKS.NOSE, MOVENET_LANDMARKS.RIGHT_EYE],
  [MOVENET_LANDMARKS.LEFT_EYE, MOVENET_LANDMARKS.LEFT_EAR],
  [MOVENET_LANDMARKS.RIGHT_EYE, MOVENET_LANDMARKS.RIGHT_EAR],
  
  // Torso
  [MOVENET_LANDMARKS.LEFT_SHOULDER, MOVENET_LANDMARKS.RIGHT_SHOULDER],
  [MOVENET_LANDMARKS.LEFT_SHOULDER, MOVENET_LANDMARKS.LEFT_HIP],
  [MOVENET_LANDMARKS.RIGHT_SHOULDER, MOVENET_LANDMARKS.RIGHT_HIP],
  [MOVENET_LANDMARKS.LEFT_HIP, MOVENET_LANDMARKS.RIGHT_HIP],
  
  // Left arm
  [MOVENET_LANDMARKS.LEFT_SHOULDER, MOVENET_LANDMARKS.LEFT_ELBOW],
  [MOVENET_LANDMARKS.LEFT_ELBOW, MOVENET_LANDMARKS.LEFT_WRIST],
  
  // Right arm
  [MOVENET_LANDMARKS.RIGHT_SHOULDER, MOVENET_LANDMARKS.RIGHT_ELBOW],
  [MOVENET_LANDMARKS.RIGHT_ELBOW, MOVENET_LANDMARKS.RIGHT_WRIST],
  
  // Left leg
  [MOVENET_LANDMARKS.LEFT_HIP, MOVENET_LANDMARKS.LEFT_KNEE],
  [MOVENET_LANDMARKS.LEFT_KNEE, MOVENET_LANDMARKS.LEFT_ANKLE],
  
  // Right leg
  [MOVENET_LANDMARKS.RIGHT_HIP, MOVENET_LANDMARKS.RIGHT_KNEE],
  [MOVENET_LANDMARKS.RIGHT_KNEE, MOVENET_LANDMARKS.RIGHT_ANKLE],
];

// MediaPipe pose connections for drawing skeleton (33 landmarks)
export const POSE_CONNECTIONS = [
  // Face
  [POSE_LANDMARKS.LEFT_EYE, POSE_LANDMARKS.RIGHT_EYE],
  [POSE_LANDMARKS.NOSE, POSE_LANDMARKS.LEFT_EYE],
  [POSE_LANDMARKS.NOSE, POSE_LANDMARKS.RIGHT_EYE],
  [POSE_LANDMARKS.LEFT_EYE, POSE_LANDMARKS.LEFT_EAR],
  [POSE_LANDMARKS.RIGHT_EYE, POSE_LANDMARKS.RIGHT_EAR],
  [POSE_LANDMARKS.MOUTH_LEFT, POSE_LANDMARKS.MOUTH_RIGHT],
  
  // Torso
  [POSE_LANDMARKS.LEFT_SHOULDER, POSE_LANDMARKS.RIGHT_SHOULDER],
  [POSE_LANDMARKS.LEFT_SHOULDER, POSE_LANDMARKS.LEFT_HIP],
  [POSE_LANDMARKS.RIGHT_SHOULDER, POSE_LANDMARKS.RIGHT_HIP],
  [POSE_LANDMARKS.LEFT_HIP, POSE_LANDMARKS.RIGHT_HIP],
  
  // Left arm
  [POSE_LANDMARKS.LEFT_SHOULDER, POSE_LANDMARKS.LEFT_ELBOW],
  [POSE_LANDMARKS.LEFT_ELBOW, POSE_LANDMARKS.LEFT_WRIST],
  [POSE_LANDMARKS.LEFT_WRIST, POSE_LANDMARKS.LEFT_THUMB],
  [POSE_LANDMARKS.LEFT_WRIST, POSE_LANDMARKS.LEFT_PINKY],
  [POSE_LANDMARKS.LEFT_WRIST, POSE_LANDMARKS.LEFT_INDEX],
  
  // Right arm
  [POSE_LANDMARKS.RIGHT_SHOULDER, POSE_LANDMARKS.RIGHT_ELBOW],
  [POSE_LANDMARKS.RIGHT_ELBOW, POSE_LANDMARKS.RIGHT_WRIST],
  [POSE_LANDMARKS.RIGHT_WRIST, POSE_LANDMARKS.RIGHT_THUMB],
  [POSE_LANDMARKS.RIGHT_WRIST, POSE_LANDMARKS.RIGHT_PINKY],
  [POSE_LANDMARKS.RIGHT_WRIST, POSE_LANDMARKS.RIGHT_INDEX],
  
  // Left leg
  [POSE_LANDMARKS.LEFT_HIP, POSE_LANDMARKS.LEFT_KNEE],
  [POSE_LANDMARKS.LEFT_KNEE, POSE_LANDMARKS.LEFT_ANKLE],
  [POSE_LANDMARKS.LEFT_ANKLE, POSE_LANDMARKS.LEFT_HEEL],
  [POSE_LANDMARKS.LEFT_ANKLE, POSE_LANDMARKS.LEFT_FOOT_INDEX],
  
  // Right leg
  [POSE_LANDMARKS.RIGHT_HIP, POSE_LANDMARKS.RIGHT_KNEE],
  [POSE_LANDMARKS.RIGHT_KNEE, POSE_LANDMARKS.RIGHT_ANKLE],
  [POSE_LANDMARKS.RIGHT_ANKLE, POSE_LANDMARKS.RIGHT_HEEL],
  [POSE_LANDMARKS.RIGHT_ANKLE, POSE_LANDMARKS.RIGHT_FOOT_INDEX],
];

// Colors for different body parts
export const POSE_COLORS = {
  FACE: '#FF6B6B',
  TORSO: '#4ECDC4',
  LEFT_ARM: '#45B7D1',
  RIGHT_ARM: '#96CEB4',
  LEFT_LEG: '#FFEAA7',
  RIGHT_LEG: '#DDA0DD',
};

// Minimum confidence threshold for pose detection
export const MIN_POSE_CONFIDENCE = 0.5;
export const MIN_LANDMARK_CONFIDENCE = 0.5;
